version: '3.4'
services:
  boinc.public.dappnode.eth:
    build: ./build
    image: 'boinc.public.dappnode.eth:0.0.1'
    environment:
      - 'PROJECT_URL=http://boinc.bakerlab.org/rosetta/'
      - API_KEY=
      - RPC_PASSWORD=dappnode
      - BOINC_REMOTE_HOST=0.0.0.0
      - CMDLINE_OPTIONS=--allow_remote_gui_rpc
    volumes:
      - 'data:/var/lib/boinc'
    restart: always
volumes:
  data: {}
